import type {
  Brain,
  BrandBrain,
  BrandDataSource,
  BrandLifecycleEvent,
  BrandMemberAssignment,
  BrandNormalizedMetric,
  BrandRawImport,
  BrandTask,
  ClientBrand,
  DecisionPrompt,
  KnowledgeNode,
  RevenueSignal,
  SeniorMemberActivity,
  TraceLog,
  TrainingTask,
  TrainingTaskAssignment,
  User,
  MemberLifecycleEvent,
} from "./domain";
import {
  muzopetBrand,
  muzopetBrandBrain,
  muzopetBrandTasks,
  muzopetDataSources,
  muzopetNormalizedMetrics,
  muzopetRawImports,
  muzopetRevenueSignals,
  muzopetSeniorMemberActivities,
} from "./brand-packs/muzopet";

export const currentUser: User = {
  id: "user-newcomer-01",
  name: "新人夥伴 A",
  role: "newcomer",
  title: "數位行銷服務訓練生",
};

export const reviewerUser: User = {
  id: "user-reviewer-yijia",
  name: "藝嘉",
  role: "reviewer",
  title: "內容品管 · 社群合規",
};

export const brains: Brain[] = [
  {
    id: "brain-jacky",
    name: "Jacky 決策腦",
    type: "jacky",
    owner: "Jacky",
    summary: "用來判斷問題分類、風險層級、下一步與是否升級處理。",
    coverage: ["問題框定", "升級條件", "品質門檻"],
  },
  {
    id: "brain-member",
    name: "成員腦：新人 60 分服務者",
    type: "member",
    owner: "Training Team",
    summary: "定義新人在任務中應該會查、會問、會交付的基本行為。",
    coverage: ["任務節奏", "交付格式", "自我檢查"],
  },
  {
    id: "brain-brand",
    name: "双云品牌腦",
    type: "brand",
    owner: "双云行銷",
    summary: "保留品牌語氣、客戶溝通方式與內容品質基準。",
    coverage: ["品牌語氣", "內容風格", "客戶脈絡"],
  },
  {
    id: "brain-method",
    name: "AGENTS 方法論節點",
    type: "method",
    owner: "Platform",
    summary: "把任務拆成可觀察、可修正、可品管的工作節點。",
    coverage: ["任務拆解", "trace log", "review loop"],
  },
];

export const clientBrands: ClientBrand[] = [
  {
    id: "brand-2clouds-demo",
    name: "2clouds Demo Brand",
    industry: "professional services",
    ownerUserId: reviewerUser.id,
    assignedMemberIds: [reviewerUser.id, currentUser.id],
    operatingStage: "active",
    positioning: "A demo client brand used to train operating judgment without exposing real client data.",
    primaryGoal: "Turn qualified consultations into retained monthly service clients.",
  },
  muzopetBrand,
];

export const brandLifecycleEvents: BrandLifecycleEvent[] = [
  {
    id: "brand-lifecycle-demo-activated",
    brandId: "brand-2clouds-demo",
    fromStage: "onboarding",
    toStage: "active",
    eventType: "activated",
    actorId: reviewerUser.id,
    occurredAt: "2026-05-01T08:00:00.000Z",
    note: "Demo brand is available for internal operating context checks.",
  },
  {
    id: "brand-lifecycle-muzopet-resumed",
    brandId: "brand-muzopet",
    fromStage: "paused",
    toStage: "resumed",
    eventType: "resumed",
    actorId: reviewerUser.id,
    occurredAt: "2026-05-01T08:30:00.000Z",
    note: "MuzoPet data and task context are ready for v1 brand operations.",
  },
];

export const brandMemberAssignments: BrandMemberAssignment[] = [
  {
    id: "assignment-demo-reviewer",
    brandId: "brand-2clouds-demo",
    memberId: reviewerUser.id,
    role: "reviewer",
    status: "active",
    assignedAt: "2026-05-01T08:00:00.000Z",
    assignedBy: reviewerUser.id,
  },
  {
    id: "assignment-demo-newcomer",
    brandId: "brand-2clouds-demo",
    memberId: currentUser.id,
    role: "newcomer_trainee",
    status: "active",
    assignedAt: "2026-05-01T08:05:00.000Z",
    assignedBy: reviewerUser.id,
  },
  {
    id: "assignment-muzopet-reviewer",
    brandId: "brand-muzopet",
    memberId: reviewerUser.id,
    role: "reviewer",
    status: "active",
    assignedAt: "2026-05-01T08:30:00.000Z",
    assignedBy: reviewerUser.id,
  },
  {
    id: "assignment-muzopet-newcomer",
    brandId: "brand-muzopet",
    memberId: currentUser.id,
    role: "newcomer_trainee",
    status: "active",
    assignedAt: "2026-05-01T08:35:00.000Z",
    assignedBy: reviewerUser.id,
  },
];

export const memberLifecycleEvents: MemberLifecycleEvent[] = [
  {
    id: "member-lifecycle-muzopet-newcomer-assigned",
    brandId: "brand-muzopet",
    memberId: currentUser.id,
    assignmentId: "assignment-muzopet-newcomer",
    fromStatus: null,
    toStatus: "active",
    eventType: "assigned",
    actorId: reviewerUser.id,
    occurredAt: "2026-05-01T08:35:00.000Z",
    note: "Newcomer can inspect MuzoPet Brand App context while still under review gates.",
  },
];

export const brandBrains: BrandBrain[] = [
  {
    id: "brand-brain-2clouds-demo",
    brandId: "brand-2clouds-demo",
    voice: "Professional, clear, practical, and calm; avoid exaggerated claims.",
    audience: "Small business owners comparing whether to outsource digital marketing operations.",
    offer: "Monthly AI-assisted marketing operations with senior review and measurable execution rhythm.",
    taboos: [
      "Do not promise guaranteed revenue.",
      "Do not imply fully automated strategy without senior review.",
      "Do not use slang or hype-heavy wording.",
    ],
    channelRules: [
      "Instagram posts should lead with a concrete business pain.",
      "Sales follow-up should name the next operational step.",
      "Monthly reports must connect content work to pipeline signals.",
    ],
    escalationRules: [
      "Escalate pricing, contract scope, or guarantee requests.",
      "Escalate when content direction changes the brand positioning.",
    ],
    updatedAt: "2026-05-01T08:00:00.000Z",
  },
  muzopetBrandBrain,
];

export const revenueSignals: RevenueSignal[] = [
  {
    id: "signal-demo-qualified-consult",
    brandId: "brand-2clouds-demo",
    type: "lead",
    label: "Qualified consultation request",
    value: "Two inbound consultations asked about monthly operating support.",
    confidence: "medium",
    observedAt: "2026-05-01T09:00:00.000Z",
  },
  {
    id: "signal-demo-retainer-risk",
    brandId: "brand-2clouds-demo",
    type: "retention",
    label: "Retainer renewal risk",
    value: "Client asked for clearer evidence that weekly content supports sales follow-up.",
    confidence: "high",
    observedAt: "2026-05-01T10:30:00.000Z",
  },
  ...muzopetRevenueSignals,
];

export const seniorMemberActivities: SeniorMemberActivity[] = [
  {
    id: "activity-demo-sophia-handoff",
    brandId: "brand-2clouds-demo",
    userId: reviewerUser.id,
    activityType: "handoff",
    summary: "Reviewer clarified that next content tasks must connect post topics to consultation quality.",
    relatedBrandTaskIds: ["brand-task-demo-content-angle"],
    createdAt: "2026-05-01T11:00:00.000Z",
  },
  {
    id: "activity-demo-strategy-review",
    brandId: "brand-2clouds-demo",
    userId: reviewerUser.id,
    activityType: "strategy",
    summary: "Senior member flagged that conversion claims need softer wording and stronger evidence.",
    relatedBrandTaskIds: ["brand-task-demo-proof-note"],
    createdAt: "2026-05-01T12:00:00.000Z",
  },
  ...muzopetSeniorMemberActivities,
];

export const brandTasks: BrandTask[] = [
  {
    id: "brand-task-demo-content-angle",
    brandId: "brand-2clouds-demo",
    title: "Draft a consultation-focused content angle",
    status: "in_progress",
    ownerUserId: currentUser.id,
    expectedOutcome: "A social post angle that speaks to qualified consultations without promising revenue.",
    revenueSignalIds: ["signal-demo-qualified-consult"],
    seniorMemberActivityIds: ["activity-demo-sophia-handoff"],
  },
  {
    id: "brand-task-demo-proof-note",
    brandId: "brand-2clouds-demo",
    title: "Connect weekly content work to monthly report proof",
    status: "queued",
    ownerUserId: currentUser.id,
    expectedOutcome: "A short proof note that links content output to sales follow-up evidence.",
    revenueSignalIds: ["signal-demo-retainer-risk"],
    seniorMemberActivityIds: ["activity-demo-strategy-review"],
  },
  ...muzopetBrandTasks,
];

export const brandDataSources: BrandDataSource[] = [...muzopetDataSources];

export const brandRawImports: BrandRawImport[] = [...muzopetRawImports];

export const brandNormalizedMetrics: BrandNormalizedMetric[] = [
  ...muzopetNormalizedMetrics,
];

export const knowledgeNodes: KnowledgeNode[] = [
  {
    id: "kg-problem-framing",
    title: "先框問題，再做內容",
    domain: "decision",
    summary: "任何交付前先確認目標、受眾、限制、成功標準與風險。",
    source: "docs/jacky-decision-layer.md",
  },
  {
    id: "kg-brand-context",
    title: "品牌腦不是素材庫",
    domain: "brand",
    summary: "品牌腦需要能回答為什麼這樣說、不能只存放可複製文案。",
    source: "docs/modules.md",
  },
  {
    id: "kg-trace-review",
    title: "每次狀態改變都留下 trace",
    domain: "quality",
    summary: "平台要記錄任務如何前進，讓 reviewer 能回放判斷脈絡。",
    source: "docs/phase-1-engineering-plan.md",
  },
  {
    id: "kg-2clouds-model",
    title: "双云三層架構：Brain / Hand / Infra",
    domain: "model",
    summary: "老闆只輸入 1-4（目標、受眾、產品、故事）；AI 行銷部接手 5-8（策略、執行、品管、回報）。Brain 層決策，Hand 層執行，Infra 層撐起工具與資料。",
    source: "docs/platform-spec.md",
  },
  {
    id: "kg-brand-pack",
    title: "如何讀懂一份品牌包（brand pack）",
    domain: "brand",
    summary: "品牌包包含老闆 Agent、主管 Agent、窗口 Agent、品牌 Agent。每個 Agent 有固定的話術禁忌、語氣規範、CTA style 與 channel rules。讀懂品牌包才能判斷內容是否符合規格。",
    source: "docs/onboarding-training-system.md",
  },
  {
    id: "kg-client-stages",
    title: "接案 Stage 0-9 流程",
    domain: "client",
    summary: "客戶從初探（Stage 0）到月報維運（Stage 9）共 10 個階段。新人需要知道目前客戶在哪個 stage、接下來要產出什麼，以及何時問題應升級給 Sophia 或 Jacky。",
    source: "docs/platform-spec.md",
  },
  {
    id: "kg-revision-feedback",
    title: "退件不是失敗，是訓練回饋",
    domain: "quality",
    summary: "needs_revision 狀態代表 reviewer 給出具體改進方向。新人的責任是看懂退件原因、修正後再送出，而不是把退件視為評分失敗。完成一次修稿通過比第一次直接通過更有訓練價值。",
    source: "docs/onboarding-training-system.md",
  },
  {
    id: "kg-escalation",
    title: "什麼問題該升級，什麼新人能處理",
    domain: "decision",
    summary: "新人能處理：已知素材的內容組裝、品牌腦查核、格式合規。必須升級：客戶承諾、策略方向改變、敏感議題、素材不足時的判斷。不確定時先升級，而不是自行假設。",
    source: "docs/jacky-decision-layer.md",
  },
  {
    id: "kg-brand-onboarding",
    title: "進入甲方品牌的四步閱讀順序",
    domain: "brand",
    summary: "進入一個新品牌前，依序閱讀：老闆 Agent（溝通風格與期望）→ 主管 Agent（服務節奏與進行中專案）→ 窗口 Agent（日常溝通規則）→ 品牌 Agent（內容規格與禁忌）。閱讀完成後整理品牌速查卡送藝嘉確認，才算完成進場。",
    source: "docs/brand-onboarding-workflow.md",
  },
  {
    id: "kg-brand-risk-levels",
    title: "品牌任務風險層級：低風險 vs. 高風險",
    domain: "brand",
    summary: "低風險（新人可獨立執行）：草稿檢查、素材整理、前情提要、合規初查。高風險（必須資深成員主責）：月報策略回顧、campaign 提案、危機回應文、任何含客戶承諾的輸出。判斷原則：任務輸出會直接影響客戶對双云的信任，則屬高風險。",
    source: "docs/brand-onboarding-workflow.md",
  },
];

export const trainingTasks: TrainingTask[] = [
  // Stage 1: 讀懂双云
  {
    id: "task-understand-2clouds",
    title: "整理双云三層架構與分工邊界",
    module: "讀懂双云",
    stage: 1,
    brief: "閱讀双云的 Brain/Hand/Infra 介紹，用自己的話整理三層架構各自負責什麼，並說明老闆輸入 1-4 與 AI 行銷部接手 5-8 的分界在哪裡。",
    expectedOutput: "三層架構說明（每層 2 句以內）、老闆與 AI 行銷部的分工邊界、1 個你目前不確定的問題。",
    recommendedBrainIds: ["brain-jacky", "brain-member"],
    recommendedKnowledgeNodeIds: ["kg-2clouds-model", "kg-escalation"],
    basePoints: 10,
  },
  // Stage 2: 讀懂品牌腦
  {
    id: "task-brand-context-card",
    title: "閱讀品牌包並整理品牌速查卡",
    module: "品牌工作台",
    stage: 2,
    brief: "你剛被分配到一個甲方品牌。依序閱讀老闆 Agent、主管 Agent、窗口 Agent、品牌 Agent 四個節點，整理一份品牌速查卡，涵蓋：品牌核心印象、內容語氣禁忌、頻道規則摘要、升級判斷標準。速查卡送藝嘉確認後才能開始承接品牌任務。",
    expectedOutput: "品牌速查卡（4 個區塊）：①品牌核心印象（1 句話）②語氣禁忌（3 點以內）③頻道規則差異（列主力平台）④升級判斷標準（分 Sophia / Jacky / 藝嘉）。",
    recommendedBrainIds: ["brain-brand", "brain-member"],
    recommendedKnowledgeNodeIds: ["kg-brand-pack", "kg-brand-onboarding", "kg-escalation"],
    basePoints: 15,
  },
  {
    id: "task-brand-check",
    title: "用品牌腦檢查一則貼文草稿",
    module: "品牌工作台",
    stage: 2,
    brief: "從 reviewer 的角度評估一則貼文草稿，判斷是否符合品牌腦的語氣規範，找出 brand 面向的具體問題並提出 3 個可執行的修正方向。",
    expectedOutput: "品牌問題清單（至少 3 點）、每點對應的修改建議、是否有需要升級 reviewer 確認的合規疑慮。",
    recommendedBrainIds: ["brain-brand", "brain-method"],
    recommendedKnowledgeNodeIds: ["kg-brand-context", "kg-brand-pack"],
    basePoints: 20,
  },
  // Stage 3: 完成第一個內容任務
  {
    id: "task-context-brief",
    title: "整理客戶內容任務前情提要",
    module: "新人 Cockpit",
    stage: 3,
    brief: "閱讀一段客戶需求，把目標、限制、素材缺口與需要升級的問題整理出來。",
    expectedOutput: "一份 5 點以內的任務前情提要，包含不確定事項。",
    recommendedBrainIds: ["brain-jacky", "brain-member"],
    recommendedKnowledgeNodeIds: ["kg-problem-framing", "kg-escalation"],
    basePoints: 15,
  },
  {
    id: "task-submit-review",
    title: "送出內容工廠最小交付",
    module: "內容工廠",
    stage: 3,
    brief: "依照前情提要完成一份社群短文，送出前做自我品管檢查。Reviewer 會從 structure（格式完整）、brand（語氣符合品牌腦）、compliance（無不當承諾）三個面向評估。",
    expectedOutput: "社群短文（300 字以內）、自我品管檢查表（structure / brand / compliance 各至少 1 點）、升級判斷說明。",
    recommendedBrainIds: ["brain-jacky", "brain-brand"],
    recommendedKnowledgeNodeIds: ["kg-problem-framing", "kg-trace-review"],
    basePoints: 25,
  },
  // Stage 4: 學會品管與修稿
  {
    id: "task-revise-after-feedback",
    title: "理解退件原因並依意見修稿",
    module: "品管中心",
    stage: 4,
    brief: "閱讀 reviewer 對一份社群草稿的退件意見，找出 structure / brand / compliance 三個面向各自的問題，重新修稿並說明每個改動的依據。",
    expectedOutput: "退件問題分析（每類至少 1 點）、修稿後版本、每個改動的說明。",
    recommendedBrainIds: ["brain-brand", "brain-method"],
    recommendedKnowledgeNodeIds: ["kg-revision-feedback", "kg-brand-context", "kg-trace-review"],
    basePoints: 20,
  },
  // Stage 5: 學會客戶服務流程
  {
    id: "task-client-service-flow",
    title: "標出客戶問題應升級的時機",
    module: "客戶服務",
    stage: 5,
    brief: "閱讀一段客戶溝通紀錄，判斷客戶目前在接案 Stage 0-9 的哪個階段，並找出至少一個應升級給 Sophia 或 Jacky 的問題，說明升級理由。",
    expectedOutput: "客戶目前 stage 判斷、升級問題說明、下一步建議。",
    recommendedBrainIds: ["brain-jacky", "brain-member"],
    recommendedKnowledgeNodeIds: ["kg-client-stages", "kg-escalation"],
    basePoints: 15,
  },
  // Stage 6: 60 分認證前測
  {
    id: "task-certification-sim",
    title: "60 分認證前測：完整模擬任務",
    module: "60 分認證",
    stage: 6,
    brief: "從一個模擬客戶需求開始，依序完成前情提要、品牌腦查核、社群短文、自我品管、trace log 留存，並在遇到不確定時正確判斷是否升級。",
    expectedOutput: "前情提要、品牌查核記錄、社群短文、自我品管檢查表、完整 trace log、升級判斷說明。",
    recommendedBrainIds: ["brain-jacky", "brain-brand", "brain-member", "brain-method"],
    recommendedKnowledgeNodeIds: [
      "kg-problem-framing",
      "kg-brand-context",
      "kg-trace-review",
      "kg-escalation",
    ],
    basePoints: 30,
  },
];

export const taskAssignments: TrainingTaskAssignment[] = [
  {
    id: "assignment-understand-2clouds",
    taskId: "task-understand-2clouds",
    userId: currentUser.id,
    status: "reviewed",
    reviewerNote: "三層架構說明清楚，下次要把「不確定的問題」寫得更具體，方便升級給 Jacky。",
  },
  {
    id: "assignment-brand-context-card",
    taskId: "task-brand-context-card",
    userId: currentUser.id,
    status: "reviewed",
    reviewerNote: "[Structure] 四個區塊都有，格式符合。[Brand] 語氣禁忌抓得準，下次可以補上具體的「禁用詞」範例，更容易對照使用。升級標準說明清楚，進場準備完成。",
  },
  {
    id: "assignment-brand-check",
    taskId: "task-brand-check",
    userId: currentUser.id,
    status: "submitted",
  },
  {
    id: "assignment-context-brief",
    taskId: "task-context-brief",
    userId: currentUser.id,
    status: "reviewed",
    reviewerNote: "能抓到主要限制，下一次要補成功標準。",
  },
  {
    id: "assignment-submit-review",
    taskId: "task-submit-review",
    userId: currentUser.id,
    status: "needs_revision",
    reviewerNote: "短文語氣偏口語，與品牌腦定義的「專業但不冷硬」有落差。請對照品牌腦 kg-brand-context，重新調整段落開頭與 CTA 用詞。",
  },
  {
    id: "assignment-revise-after-feedback",
    taskId: "task-revise-after-feedback",
    userId: currentUser.id,
    status: "not_started",
  },
  {
    id: "assignment-client-service-flow",
    taskId: "task-client-service-flow",
    userId: currentUser.id,
    status: "not_started",
  },
  {
    id: "assignment-certification-sim",
    taskId: "task-certification-sim",
    userId: currentUser.id,
    status: "not_started",
  },
];

export const decisionPrompts: DecisionPrompt[] = [
  {
    taskId: "task-understand-2clouds",
    problemFraming: "這不是記憶任務，而是建立工作心智模型。重點是能說明分工邊界，而不是背誦架構圖。",
    recommendedModel: "三層架構（Brain/Hand/Infra）、老闆輸入邊界、AI 行銷部接手邊界",
    relatedKnowledgeNodeIds: ["kg-2clouds-model"],
    suggestedNextStep: "先說明每層「誰負責什麼決定」，再對照你自己在組織裡的角色。",
    escalationCondition: "如果你對双云的服務範圍或角色定位不確定，先問 Jacky 再完成摘要。",
  },
  {
    taskId: "task-brand-context-card",
    problemFraming: "你不是在「讀資料」，而是在建立一個工作地圖。速查卡的目的是讓你在做任何任務前，5 分鐘內能回想起這個品牌的邊界。",
    recommendedModel: "老闆 Agent → 主管 Agent → 窗口 Agent → 品牌 Agent（依序閱讀）",
    relatedKnowledgeNodeIds: ["kg-brand-pack", "kg-brand-onboarding"],
    suggestedNextStep: "先把四個 Agent 各讀一遍，再依照速查卡格式填寫，填完對照品牌包確認沒有漏掉禁忌。",
    escalationCondition: "品牌包裡有矛盾的規格（例如不同 Agent 對語氣的描述衝突），或合規邊界不清楚，先問藝嘉確認再完成速查卡。",
  },
  {
    taskId: "task-brand-check",
    problemFraming: "判斷草稿是否能代表品牌，而不是只看文字是否順。",
    recommendedModel: "品牌語氣、受眾理解、證據密度、行動呼籲",
    relatedKnowledgeNodeIds: ["kg-brand-context", "kg-brand-pack"],
    suggestedNextStep: "列出每個問題對應的品牌風險，再提出可執行修正。",
    escalationCondition: "涉及品牌定位、敏感議題或客戶承諾時升級。",
  },
  {
    taskId: "task-context-brief",
    problemFraming: "這不是寫文案任務，先判斷客戶要解決的營運問題。",
    recommendedModel: "目標、受眾、限制、缺口、升級條件",
    relatedKnowledgeNodeIds: ["kg-problem-framing"],
    suggestedNextStep: "把需求拆成已知資訊與待確認問題，再決定是否能開始交付。",
    escalationCondition: "客戶目標不明、素材不足、或承諾範圍超出新人權限時升級。",
  },
  {
    taskId: "task-submit-review",
    problemFraming: "交付品要能被 reviewer 快速檢查來源、判斷與修改理由。",
    recommendedModel: "交付內容、檢查表、trace log、review note",
    relatedKnowledgeNodeIds: ["kg-problem-framing", "kg-trace-review"],
    suggestedNextStep: "先完成短文，再附上自我檢查與不確定點。",
    escalationCondition: "如果內容需要客戶新素材或需要改變策略方向，先升級。",
  },
  {
    taskId: "task-revise-after-feedback",
    problemFraming: "你收到退件，這是訓練，不是懲罰。先讀懂退件原因，再動手修稿。",
    recommendedModel: "structure 問題 / brand 問題 / compliance 問題（三類各別分析）",
    relatedKnowledgeNodeIds: ["kg-revision-feedback", "kg-brand-context"],
    suggestedNextStep: "把退件意見拆成三類問題，逐一對應品牌腦的規範，修稿後說明每個改動的依據。",
    escalationCondition: "如果退件原因不清楚，或修改方向涉及品牌策略改變，升級給 reviewer 再確認。",
  },
  {
    taskId: "task-client-service-flow",
    problemFraming: "你要判斷的是「現在客戶在哪個 stage」以及「什麼問題超出新人的決策邊界」。",
    recommendedModel: "接案 Stage 0-9、升級條件、新人可處理 vs. 必須升級清單",
    relatedKnowledgeNodeIds: ["kg-client-stages", "kg-escalation"],
    suggestedNextStep: "先標出客戶 stage，再掃描溝通紀錄裡有沒有承諾類、策略類或敏感類問題。",
    escalationCondition: "所有涉及客戶承諾、合約、策略調整的問題都要升級。",
  },
  {
    taskId: "task-certification-sim",
    problemFraming: "這是完整流程測驗。你要展示的不是交付品有多好，而是整個流程有沒有走完、有沒有留下 trace、有沒有在對的時機升級。",
    recommendedModel: "前情提要 → 品牌查核 → 內容交付 → 自我品管 → trace log → 升級判斷",
    relatedKnowledgeNodeIds: ["kg-problem-framing", "kg-trace-review", "kg-escalation"],
    suggestedNextStep: "依序完成六個步驟，每個步驟產出獨立的文件或記錄，最後彙整成一份交付包。",
    escalationCondition: "在任何一個步驟中，只要遇到不確定就先暫停、升級，再繼續。",
  },
];

export const traceLogs: TraceLog[] = [
  {
    id: "trace-understand-started",
    assignmentId: "assignment-understand-2clouds",
    actorId: currentUser.id,
    action: "task_started",
    fromStatus: "not_started",
    toStatus: "in_progress",
    createdAt: "2026-04-28T09:00:00.000Z",
  },
  {
    id: "trace-understand-submitted",
    assignmentId: "assignment-understand-2clouds",
    actorId: currentUser.id,
    action: "task_submitted",
    fromStatus: "in_progress",
    toStatus: "submitted",
    createdAt: "2026-04-28T10:15:00.000Z",
  },
  {
    id: "trace-understand-reviewed",
    assignmentId: "assignment-understand-2clouds",
    actorId: reviewerUser.id,
    action: "review_created",
    fromStatus: "submitted",
    toStatus: "reviewed",
    createdAt: "2026-04-28T14:00:00.000Z",
  },
  {
    id: "trace-context-brief-reviewed",
    assignmentId: "assignment-context-brief",
    actorId: reviewerUser.id,
    action: "review_created",
    fromStatus: "submitted",
    toStatus: "reviewed",
    createdAt: "2026-04-30T08:30:00.000Z",
  },
  {
    id: "trace-submit-review-started",
    assignmentId: "assignment-submit-review",
    actorId: currentUser.id,
    action: "task_started",
    fromStatus: "not_started",
    toStatus: "in_progress",
    createdAt: "2026-04-30T09:00:00.000Z",
  },
  {
    id: "trace-submit-review-submitted",
    assignmentId: "assignment-submit-review",
    actorId: currentUser.id,
    action: "task_submitted",
    fromStatus: "in_progress",
    toStatus: "submitted",
    createdAt: "2026-04-30T11:30:00.000Z",
  },
  {
    id: "trace-submit-review-needs-revision",
    assignmentId: "assignment-submit-review",
    actorId: reviewerUser.id,
    action: "revision_requested",
    fromStatus: "submitted",
    toStatus: "needs_revision",
    createdAt: "2026-04-30T15:00:00.000Z",
  },
  {
    id: "trace-brand-context-card-started",
    assignmentId: "assignment-brand-context-card",
    actorId: currentUser.id,
    action: "task_started",
    fromStatus: "not_started",
    toStatus: "in_progress",
    createdAt: "2026-04-29T09:00:00.000Z",
  },
  {
    id: "trace-brand-context-card-submitted",
    assignmentId: "assignment-brand-context-card",
    actorId: currentUser.id,
    action: "task_submitted",
    fromStatus: "in_progress",
    toStatus: "submitted",
    createdAt: "2026-04-29T10:30:00.000Z",
  },
  {
    id: "trace-brand-context-card-reviewed",
    assignmentId: "assignment-brand-context-card",
    actorId: reviewerUser.id,
    action: "review_created",
    fromStatus: "submitted",
    toStatus: "reviewed",
    createdAt: "2026-04-29T14:00:00.000Z",
  },
  {
    id: "trace-brand-check-started",
    assignmentId: "assignment-brand-check",
    actorId: currentUser.id,
    action: "task_started",
    fromStatus: "not_started",
    toStatus: "in_progress",
    createdAt: "2026-05-01T08:30:00.000Z",
  },
  {
    id: "trace-brand-check-submitted",
    assignmentId: "assignment-brand-check",
    actorId: currentUser.id,
    action: "task_submitted",
    fromStatus: "in_progress",
    toStatus: "submitted",
    createdAt: "2026-05-01T09:15:00.000Z",
  },
];
